version: "3"
services:
  node:
    tty: true
    build: ./docker
    ports:
      - "3000:3000"
    volumes:
      - ./:/opt/app
    environment:
      AWS_REGION: ap-northeast-1
      AWS_ACCESS_KEY_ID: local
      AWS_SECRET_ACCESS_KEY: dummy
      S3_ENDPOINT: "http://storage:9090"
      S3_BUCKET: "video-bucket"
      DB_HOST: "db"
      DB_USERNAME: "postgres"
      DB_PASSWORD: "password"
      DB_DATABASE: "mock"
      REDIS_HOST: "cache"
    depends_on:
      - db
      - cache
      - storage
  frontend:
    build:
      context: ./frontend
    ports:
      - "3001:3001"
    volumes:
      - ./frontend:/app  # ホストマシンのfrontendディレクトリを
    tty: true
    environment:
      - CHOKIDAR_USEPOLLING=true #ホットリロードを行う設定
      - CORS_ORIGIN=http://localhost:3000 #CORS用
      - REACT_APP_CLIENT_URL=http://localhost:3000
      - REACT_APP_S3_ENDPOINT=http://localhost:9090
  db:
    image: "postgres:15-alpine"
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=mock
    volumes:
      - db-store:/var/lib/postgresql/data
  cache:
    image: "redis:7"
    ports:
      - "6379:6379"
  storage:
    image: "adobe/s3mock"
    ports:
      - "9090:9090"
    environment:
      initialBuckets: video-bucket
      debug: true
volumes:
  db-store:
